/*****************************************************************************
** (C) Chris Wood 1995.
**
** RESOURCE.H - Resource file IDs.
**
******************************************************************************
*/

/* Check for previous inclusion. */
#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/**** Menu IDs. *************************************************************/
#define IDM_EXIT		100		/* Exit application. */
#define IDM_ABOUT		200		/* About the Application. */

/**** String IDs. ***********************************************************/
/* Misc. */
#define IDS_APPNAME		1000		/* Application name. */

#endif /* _RESOURCE_H_ */
