//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by MAILTOSS.RC
//
#define IDS_PROGRAM                     1
#define IDS_VERSION                     2
#define IDS_COPYRIGHT                   3
#define IDC_SOURCEDIR                   1000
#define IDC_FILENAME                    1001
#define IDC_USERNAME                    1002
#define IDC_SERVERNAME                  1003
#define IDC_POSTMASTER                  1004
#define IDC_STATIC                      -1
#define IDC_UNUSED                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
