/*****************************************************************************
** (C) Chris Wood 1995.
**
** AF.H - Main include file.
**
******************************************************************************
*/

/* Check for previous inclusion. */
#ifndef _AF_H_
#define _AF_H_

/**** Turn off certain compiler warnings. ***********************************/
#pragma warning(disable:4505)		/* Unreferenced local function removed. */
#pragma warning(disable:4100)		/* Unreferenced formal parameter. */
#pragma warning(disable:4001)		/* Single line comment. */
#pragma warning(disable:4209)		/* Benign typedef redefinition. */
#pragma warning(disable:4213)		/* Cast on l-value. */

/**** Include major headers. ************************************************/
#include <windows.h>
#include <windowsx.h>
#include "basedefs.h"
#include "debug.h"

#endif /* _AF_H_ */
