/*****************************************************************************
** (C) Chris Wood 1995.
**
** RESOURCE.H - Resource file IDs.
**
******************************************************************************
*/

/* Check for previous inclusion. */
#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/**** String IDs. ***********************************************************/
/* Misc. */
#define IDS_APPNAME		1000

#endif /* _RESOURCE_H_ */
