/*****************************************************************************
** (C) Chris Wood 1995.
**
** MENURSC.H - Menu resource IDs.
**
******************************************************************************
*/

/* Check for previous inclusion. */
#ifndef _MENURSC_H_
#define _MENURSC_H_

/* Debug. */
#define IDM_APP          100       /* Set application name. */
#define IDM_EXIT		101		/* Exit application. */

/* Edit. */
#define IDM_COPY		200		/* Copy to clipboard. */
#define IDM_CLEAR		201		/* Clear window. */

/* Help. */
#define IDM_ABOUT		800		/* About the Application. */

#endif /* _MENURSC_H_ */
