//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by APP.RC
//
#define ABOUT_APPNAME                   102
#define ABOUT_COPYRIGHT                 103
#define ABOUT_EMAILADDR                 104
#define ABOUT_VERSION                   105
#define IDC_CLASSNAME                   1000
#define IDC_NOTIFYTHREADS               1001
#define IDC_NOTIFYDLLS                  1002
#define IDC_NOTIFYPROCESSES             1005
#define IDC_LABEL                       -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
