//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by APP16.RC
//
#define _APS_3D_CONTROLS                1
#define ID_FILE_POPUP                   100
#define ID_FILE_EXPORT                  101
#define ID_FILE_PRINT                   102
#define ID_FILE_PRINT_SETUP             103
#define ID_FILE_EXIT                    104
#define ID_SESSION_POPUP                200
#define ID_SESSION_CLOCK_IN             201
#define ID_SESSION_SWITCH_TASKS         202
#define ID_SESSION_CLOCK_OUT            203
#define ID_SESSION_EDIT                 204
#define ID_PRUNE_POPUP                  300
#define ID_PRUNE_SESSIONS               301
#define ID_PRUNE_TASKS                  302
#define ID_HELP_POPUP                   400
#define ID_HELP_CONTENTS                401
#define ID_HELP_ABOUT                   402
#define IDC_CURRENT_TIME                1001
#define IDC_CURRENT_DATE                1002
#define IDC_NOW                         1003
#define IDC_SESSION_DATE                1004
#define IDC_ON_AT                       1005
#define IDC_SESSION_TIME                1006
#define IDC_DATE                        1007
#define IDC_SESSION_LEN                 1008
#define IDC_TIME                        1009
#define IDC_SESSION_TASK                1010
#define IDC_TO_DATE                     1011
#define IDC_TASK                        1012
#define IDC_TOTAL_TODAY                 1013
#define IDC_PREV_TASK                   1014
#define IDC_TOTAL_WEEK                  1015
#define IDC_OUT_DATE                    1016
#define IDC_NEXT_TASK                   1017
#define IDC_TOTAL_MONTH                 1018
#define IDC_OUT_TIME                    1019
#define IDC_TOTAL_TOTAL                 1020
#define IDC_SESSIONS                    1021
#define IDC_ADD                         1022
#define IDC_MODIFY                      1023
#define IDC_IN_DATE                     1024
#define IDC_DELETE                      1025
#define IDC_IN_TIME                     1026
#define IDC_ALL                         1027
#define IDC_BEFORE                      1028
#define IDC_PRINTER                     1029
#define IDC_PORT                        1030
#define IDC_BROWSE                      1035
#define IDC_FILENAME                    1036
#define IDC_TASKS                       1037
#define IDC_SELECT                      1038
#define IDC_FROM_DATE                   1042
#define IDC_GROUPING                    1045
#define IDC_PERIOD                      1046
#define IDD_MAIN_DIALOG                 5000
#define IDD_ABOUT_DIALOG                5001
#define IDD_CLOCK_IN_DIALOG             5002
#define IDD_CLOCK_OUT_DIALOG            5003
#define IDD_SWITCH_TASKS_DIALOG         5004
#define IDD_EDIT_SESSIONS_DIALOG        5005
#define IDD_ADD_SESSION_DIALOG          5006
#define IDD_MODIFY_SESSION_DIALOG       5007
#define IDD_PRUNE_SESSIONS_DIALOG       5008
#define IDD_EXPORT_DIALOG               5009
#define IDD_PRINT_DIALOG                5010
#define IDD_PRUNE_TASKS_DIALOG          5011
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         112
#define _APS_NEXT_CONTROL_VALUE         1047
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
