/******************************************************************************
** (C) Chris Wood 1998
**
** MODULE:		WCLRSC.H
** COMPONENT:	Windows C++ Library.
** DESCRIPTION:	Predefined resource IDs.
**
*******************************************************************************
*/

/******************************************************************************
**
**	General application strings.
**	(Only IDS_APP_TITLE must be defined)
**
*******************************************************************************
*/

#define IDS_APP_TITLE                   1
#define	IDS_HELP_FILE					2
#define IDS_CFG_FILE					3

/******************************************************************************
**
**	Window class names.
**	(only IDS_FRAME_WND must be defined)
**
*******************************************************************************
*/

#define IDS_FRAME_WND             		50
#define IDS_TOOLBAR_WND           		51
#define IDS_STATUSBAR_WND              	52
#define IDS_HINTBAR_WND              	53
#define IDS_PROGRESSBAR_WND            	54
#define IDS_VIEW_WND					55

/******************************************************************************
**
**	System Menu hints.
**
*******************************************************************************
*/

#define	IDS_SYS_RESTORE					61728
#define	IDS_SYS_MOVE					61456
#define	IDS_SYS_SIZE					61440
#define	IDS_SYS_MINIMIZE				61472
#define	IDS_SYS_MAXIMIZE				61488
#define	IDS_SYS_CLOSE					61536
#define	IDS_SYS_SWITCH					61744

/******************************************************************************
**
**	General application resources.
**
*******************************************************************************
*/

#define ID_APP_ICON						1
#define ID_APP_MENU						2
#define ID_APP_ACCEL					3
#define	ID_APP_TOOLBAR					4
