/*****************************************************************************
** (C) Chris Wood 1995.
**
** MDALIB.H - MDA Library header file for use in the application.
**
******************************************************************************
*/

/* Check for previous inclusion. */
#ifndef _MDALIB_H_
#define _MDALIB_H_

#include "mdadefs.h"
#include "mdafuncs.h"

#endif /* _MDALIB_H_ */
